name: Release
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from manifest.json
        id: manifest
        run: |
          VERSION=$(jq -r '.version' custom_components/lg_ess/manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"


      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.manifest.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version already released"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Found new version"
          fi

      - name: Create GitHub Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.manifest.outputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}